Portfolio feature
ernestkorir/my-portfolio pull request #15
Opened 2022-10-13 18:17 UTC by ernestkorir

Display Content through Javascript to the template in an HTML file

Thanks for reviewing my PR 
Hoping for the best

2022-10-13 18:47 UTC, ShoiraTa requested changes
Hi @ernestkorir ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username [@shoirata].


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 18:47 UTC, ShoiraTa commented on script.js
> +    let cardTemplate = projectsDiv.querySelector('#project-template');
- [ ] When I click on project I get the popup with completely different topic and images. The same popup shows up on every click,. 

https://user-images.githubusercontent.com/77038610/195678879-662c4df5-506c-4e20-963b-0bb0ba771117.mp4

2022-10-13 18:47 UTC, ShoiraTa commented on style.css
>      border-radius: 24px;
- [ ] The popup should follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins)

Your desktop design   | Figma desktop design
------------- | -------------
 <img width="921" alt="Screenshot 2022-10-13 at 21 40 50" src="https://user-images.githubusercontent.com/77038610/195679621-e7707e7a-1980-49c9-8107-d18de2152a4d.png"> |  <img width="507" alt="Screenshot 2022-10-13 at 21 41 10" src="https://user-images.githubusercontent.com/77038610/195679688-ec130201-ab45-4e5b-abd7-a7d59b38dd7b.png">

Your mobile design  | Figma mobile design
------------- | -------------
<img width="288" alt="Screenshot 2022-10-13 at 21 42 46" src="https://user-images.githubusercontent.com/77038610/195680004-a805bea8-7615-4145-bdee-4b3de6b63357.png"> | <img width="221" alt="Screenshot 2022-10-13 at 21 43 32" src="https://user-images.githubusercontent.com/77038610/195680141-bb03345c-6846-4f7c-8dfc-a57837ee2527.png">

Please make sure that you have the same layout, eg., text placement margins paddings etc.

2022-10-14 11:47 UTC, levy002 requested changes
## Hello @ernestkorir   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-14 11:47 UTC, levy002 commented on style.css
> +  }
- [ ] Kindly make sure to meet the provided Figma as requested by the previous reviewer. :wink: 

   - ### Your designs
   ![image](https://user-images.githubusercontent.com/87197412/195839045-dd5bd824-9f48-45dc-8a98-c2d88a8dc802.png)

    ![image](https://user-images.githubusercontent.com/87197412/195839137-85300f76-1ace-4725-8579-9e0d401022de.png)


   - ### Figma designs
   ![image](https://user-images.githubusercontent.com/87197412/195839297-32d3968a-2b1f-486a-8618-1854ec775ee9.png)

   ![image](https://user-images.githubusercontent.com/87197412/195839338-3fe93abd-0a61-483e-a68c-325a6fe0e5c8.png)

2022-10-14 13:23 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅
## Hi @ernestkorir 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media4.giphy.com/media/26DOoDwdNGKAg6UKI/giphy-downsized-medium.gif"/> 

## Highlights:
* Well written PR description ✔️ 
* All tests passed ✔️ 

## Optional suggestions:
- [ ] It would be better if the popup window wasn't a bit transparent, it's a bit hard to look at the content this way 👍 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-14 14:02 UTC, merged